### ISSUE TITLE
is an ARM version possible? 

### ISSUE THREAD

**Issue by bennyb0y** [jeanralphaviles/prometheus_speedtest#12]
```
pi@pi:~ $ docker --version
Docker version 19.03.5, build 633a0ea
```

```
pi@pi:~ $ uname -a
Linux pi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

```
pi@pi:~ $ docker run --rm -i --name prometheus_speedtest -p 9516:9516/tcp jraviles/prometheus_speedtest:latest
standard_init_linux.go:211: exec user process caused "exec format error"
```

I would love to run this on a Raspberry pi.. any chance for an ARM version?

**Comment by jeanralphaviles** [comment]
> I would love to run this on a Raspberry pi.. any chance for an ARM version?

Absolutely! I recently added multi-arch image support for one of my other repos, [github.com/jeanralphaviles/dump1090-docker](https://github.com/jeanralphaviles/dump1090-docker). It's straightforward to support. I've got #13 updating my instructions to upload these images to Docker Hub.

Go ahead, try it out, and tell me if it works.

**Comment by bennyb0y** [comment]
As much as I love flight aware, i think you sent me the wrong link :). Trying the arm version now.
