### ISSUE TITLE
Selecting Server causing error

### ISSUE THREAD

**Issue by dpang91** [jeanralphaviles/prometheus_speedtest#36]
Hi,

Have set up the following via docker compose and tied into my current prometheus instance, Speedtest is able to run when not defining a specific server but fails to locate the local speedtest server which I used to use when defined as a command. The following error is present:
<img width="875" alt="Screenshot 2020-11-27 at 3 53 32 pm" src="https://user-images.githubusercontent.com/49047334/100466395-c3b5dc00-30c8-11eb-994e-5a0a5cc2fee9.png">

Note, the server ID I have 3448 which is a valid server in Manchester GB.

Thanks

**Comment by jeanralphaviles** [comment]
This is an artifact from [speedtest-cli](https://github.com/sivel/speedtest-cli). It seems that `speedtest-cli` only matches nearby servers, not any server globally.

In other words, if your server does not show up in `speedtest-cli --list` then you'll get a `NoMatchedServers` error.

```
$ speedtest-cli --list | grep 3448
<EOF>
$ speedtest-cli --server 3448
Retrieving speedtest.net configuration...
Testing from (xxx.yyy.zzz.243)...
Retrieving speedtest.net server list...
ERROR: No matched servers: 3448
```
