### ISSUE TITLE
Grafana dashboard template available?

### ISSUE THREAD

**Issue by flow23** [jeanralphaviles/prometheus_speedtest#46]
Hi,

is there a grafana dashboard template available for users to just import?
Maybe make it available here: https://grafana.com/grafana/dashboards

Best regards,
Florian

**Comment by jeanralphaviles** [comment]
That's a great idea, never heard of Grafana templates. Doğukan Çağatay created one for prometheus_speedtest 2 years ago at https://grafana.com/grafana/dashboards/11229. It looks pretty good, I'll link to it on the readme.
